name: Build

on:
  workflow_call:
    inputs:
      targets:
        description: 'List of targets to build'
        required: true
        type: string
      push:
        description: 'Push built images to registry'
        required: false
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=ref,event=branch

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          targets: ${{ inputs.targets }}
          push: ${{ inputs.push }}
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file }}
            cwd://${{ steps.github-meta.outputs.bake-file }}
